### ISSUE TITLE
Misaligned Output Screen

### ISSUE THREAD

**Issue by Enverex** [libretro/libretro-vecx#12]
I've been trying to set up the Vectrex overlays recently and noticed that they don't seem to line up at all. As far as I can tell the overlays themselves are the correct aspect ratio, but no matter the amount of fudging, it doesn't seem possible to make the two line up. The main problem appears to be the screen itself is too far down. Here are two examples of the current state:

Overlay scale 1:
![image](https://cloud.githubusercontent.com/assets/958670/25852671/0bb60ba8-34c2-11e7-8ea7-885a85739ca2.png)

Overlay scale 0.90:
![image](https://cloud.githubusercontent.com/assets/958670/25852685/177ba722-34c2-11e7-97dc-630ccaecb832.png)

**Comment by hizzlekizzle** [comment]
Is that with integer scaling enabled?

**Comment by Enverex** [comment]
No, but it doesn't help. Here it is in integer scaled mode.

![image](https://cloud.githubusercontent.com/assets/958670/25867801/a1974d3c-34f2-11e7-9b16-6dc756c101f8.png)

**Comment by arpruss** [comment]
The issue is that overlay needs to stick out beyond the vector drawing area. I think the way to fix it is to tweak libretro.c to put a small margin around the drawing area. The only down-side is that games without overlays will have their display slightly reduced. One could, of course, make this optional and set it in the overlay .cfg file, but that makes things more complicated.

**Comment by arpruss** [comment]
I just submitted a PR that allows one to scale and shift the display to fit overlays.
